export enum EntryState {
  EMAIL_INPUT = 'EMAIL_INPUT',
  OTP_INPUT = 'OTP_INPUT',
  SUCCESS = 'SUCCESS',
  VEHICLE_MANAGER = 'VEHICLE_MANAGER',
  ACCOUNT_MANAGER = 'ACCOUNT_MANAGER',
  ADVANCED_TRANSACTION = 'ADVANCED_TRANSACTION',
  SIGN_MESSAGE = 'SIGN_MESSAGE',
  ERROR = 'ERROR',
  LOADING = 'LOADING',
  LOGOUT = 'LOGOUT',
  PROVISION_DEVELOPER_LICENSE = 'PROVISION_DEVELOPER_LICENSE',
}

export enum AuthParam {
  AltTitle = 'altTitle',
  BrandName = 'brandName',
  ClientId = 'clientId',
  EntryState = 'entryState',
  ExpirationDate = 'expirationDate',
  ForceEmail = 'forceEmail',
  MessageData = 'messageData',
  Onboarding = 'onboarding',
  PermissionTemplateId = 'permissionTemplateId',
  Permissions = 'permissions',
  PowertrainTypes = 'powertrainTypes',
  RedirectUri = 'redirectUri',
  TransactionData = 'transactionData',
  PrivacyPolicyUrl = 'privacyPolicyUrl',
  TosUrl = 'tosUrl',
  Utm = 'utm',
  VehicleMakes = 'vehicleMakes',
  Vehicles = 'vehicles',
  ExistingTokenId = 'existingTokenId',
  ExistingClientId = 'existingClientId',
}
