export enum MessageEventType {
  READY = 'READY',
  AUTH_INIT = 'AUTH_INIT',
  AUTH_RESPONSE = 'authResponse',
  TRANSACTION_RESPONSE = 'transactionResponse',
  MESSAGE_RESPONSE = 'messageResponse',
  LOGOUT = 'logout',
  DIMO_ERROR = 'DIMO_ERROR',
}

export enum EventTypes {
  EXECUTE_ADVANCED_TRANSACTION = 'EXECUTE_ADVANCED_TRANSACTION',
  SHARE_VEHICLES_DATA = 'SHARE_VEHICLES_DATA',
  SHARE_ACCOUNT_DATA = 'SHARE_ACCOUNT_DATA',
  SIGN_MESSAGE = 'SIGN_MESSAGE',
  LOGOUT = 'LOGOUT',
}
