export enum PERMISSIONS {
  NONLOCATION_TELEMETRY = 'NONLOCATION_TELEMETRY',
  COMMANDS = 'COMMANDS',
  CURRENT_LOCATION = 'CURRENT_LOCATION',
  ALLTIME_LOCATION = 'ALLTIME_LOCATION',
  CREDENTIALS = 'CREDENTIALS',
  STREAMS = 'STREAMS',
  RAW_DATA = 'RAW_DATA',
  APPROXIMATE_LOCATION = 'APPROXIMATE_LOCATION',
}
